[book]
authors = ["Manas Harbola"]
language = "en"
multilingual = false
src = "src"
title = "A Guide to the CHIP-8"

[build]
build-dir = "docs"

[preprocessor.glossary-injector]
command = "python3 glossary_injector.py"